language: ruby
rvm:
  - '2.4.0'
env:
  - DB=mysql
install:
  - sudo apt-get update
  - sudo apt-get install libfreeimage3 libfreeimage-dev
  # wkhtmltopdf
  - sudo apt-get install libqt4-gui libqt4-network libqt4-webkit libxrender-dev xorg
  - sudo apt-get install xfonts-75dpi
  - wget 'http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb'
  - sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  - bundle install --jobs=1 --retry=3 --deployment --without production
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  # bundle exec rake pending Firefox 47.0.1 and geckodriver
  - bundle exec rspec -t ~js
before_script:
  - mysql -e 'create database zmey_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.sample.yml config/secrets.yml
  # Selenium WebDriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
