language: ruby
rvm:
  - '2.2.2'
env:
  - DB=mysql
install:
  - sudo apt-get update
  - sudo apt-get install libfreeimage3 libfreeimage-dev
  - bundle install --without production --retry 3
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - mysql -e 'create database zmey_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.sample.yml config/secrets.yml
  # Selenium WebDriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
