# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: a2afb54440eb0c0b4ceeeb3d602a65141bc98317ecf6dafbd49169cbb7539be7870c6255988b394626ac02ad25268e07f35099f14c14c54e4b8be33ff34eb87f

stripe_api_key: sk_test_PUTYOURKEYHERE
stripe_endpoint_secret: whsec_PUTYOURKEYHERE
